services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # plugin service
    exchange_rates_updater_plugin_service:
        class: Acme\SyliusExchangeRatesUpdaterPlugin\Service\ExchangeRatesUpdater

    # plugin commands
    exchange_rates_updater_plugin_update_command:
        class: Acme\SyliusExchangeRatesUpdaterPlugin\Command\SyliusExchangeRatesUpdateCommand
